# Generated by Django 6.1.1 on 2026-09-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='artist_headers/')),
                ('theme_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('custom_css', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('template_choice', models.CharField(default='default', max_length=50)),
                ('font_choice', models.CharField(blank=True, default='system', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.artistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('invoice_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.product')),
            ],
        ),
    ]
